emoji = " ðŸ‡©ðŸ‡²"
code = """
r 0 0 * * 0 * #046a38
r 4 0 1 * 0 * #ffcd00
r 0 4 * 1 0 * #ffcd00
r 7 0 1 * 0 * #ffffff
r 0 7 * 1 0 * #ffffff
r 5 0 2 * 0 * #000000
r 0 5 * 2 0 * #000000
c 3 3 3 3 0 * #d50032
"""
