name = "Epipremnum Aureum"

watering = [
	"let dry between watering",
	"until top 2 cm are dry",
]

location = [
	"indirect sunlight",
]

fertilizing = [
	"growing season: every two weeks",
]

pruning = [
	"only fully-yellow leaves",
]
