name = "Lychee"

watering = [
	"lots of water during all year",
	"mist occasionally",
]

location = [
	"direct sunlight",
]

fertilizing = [
	"growing season: every month",
]

pruning = [
	"Prune at the end of winter",
]
